on: 
  push:
    tags: 
      - '*.*.*'

permissions:
  contents: write

name: Publish Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.72.1

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run wasm-build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css pkg/obsidian_typst_bg.wasm